name: commit
on: [push]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - uses: ./.github/run-tests

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "dist/dxrando"
        path: DXRando.zip
