name: commit
'on':
  - push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: ./.github/run-tests

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: DXRando
          path: dist/DXRandoInstaller.exe

      - name: Upload installer warnings
        uses: actions/upload-artifact@v3
        with:
          name: installerwarnings.txt
          path: build/installer/warn-installer.txt

      - name: Upload Bingo Viewer
        uses: actions/upload-artifact@v3
        with:
          name: BingoViewer
          path: dist/BingoViewer.exe

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3 binutils

      - uses: ./.github/run-tests

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: DXRando-linux
          path: dist/DXRandoInstaller

      - name: Upload installer warnings
        uses: actions/upload-artifact@v3
        with:
          name: installerwarningslinux.txt
          path: build/installer/warn-installer.txt

      - name: Upload Bingo Viewer
        uses: actions/upload-artifact@v3
        with:
          name: BingoViewer-linux
          path: dist/BingoViewer
