name: commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - run: pip3 install -r installer/requirements.txt 2>&1
      shell: bash
    - name: Python check
      run: python -m compileall -q .
    - name: Run tests
      run: python installer/tests.py
