name: commit
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install Python Deps
      run: pip3 install tk pyinstaller
    - name: Python check
      run: python -m compileall -q .
    - name: Build bingo watcher
      run: pyinstaller BingoDisplay.py --onefile --noconsole
    - name: Show results
      run: tree /F
    - name: dir
      run: dir
    - name: dir dist
      run: dir dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "deus-ex-randomizer"
        path: dist/BindoDisplay.exe
