name: commit
on: [push]
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - uses: ./.github/run-tests

    - run: cp installer/shortcuts/* ./dist/
      shell: bash

    - run: Compress-Archive -Path dist/* -Destination DXRando.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DXRando
        path: "DXRando.zip"
  linux:
    runs-on: ubuntu-latest
    defaults:
        run:
          # Must be explicit for proper pipefail support
          shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - run: sudo apt-get update -y
    - run: sudo apt-get install -y python3-tk idle3 binutils

    - uses: ./.github/run-tests

    # TODO: maybe try this https://medium.com/@philipp.h/reduce-clutter-when-using-pyinstaller-in-one-directory-mode-b631b9f7f89b
    #- run: ln -s dxrando/installer "DXRando Installer"
    #  working-directory: ./dist
    #- run: ln -s dxrando/BingoViewer "BingoViewer"
    #  working-directory: ./dist

    - run: zip --symlinks -r DXRando.zip .
      working-directory: ./dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DXRando-linux
        path: "dist/DXRando.zip"
