name: commit
'on':
  - push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: ./.github/run-tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DXRando
          path: dist/DXRando/DXRando.zip

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3 binutils

      - uses: ./.github/run-tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DXRando-linux
          path: dist/DXRando/DXRando.zip
