name: commit
on: [push]
jobs:
  build:
    runs-on: windows-latest
    #defaults:
      #run:
        # Must be explicit for proper pipefail support
        #shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - run: pip3 install -r installer/requirements.txt 2>&1
      shell: bash
    - name: Python check
      run: python -m compileall -q .
    - name: Run tests
      run: python installer/tests.py

    - name: Build installer
      run: pyinstaller installer/installer.spec

    # make sure we don't need the .app folder, specifically for MacOS
    - run: rm -rf dist/dxrando/installer.app
      shell: bash
    - run: ./dist/dxrando/installer.exe --version 2>&1
      shell: bash

    - run: Compress-Archive -Path dist/* -Destination DXRando.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "DXRando"
        path: DXRando.zip
