name: release-installer
'on':
  release:
    types:
      - published

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: ./.github/run-tests

      - name: Upload Release Asset DXRando.zip
        id: upload-release-asset-dxrando-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/DXRando/DXRando.zip
          asset_name: DXRandoInstaller.zip

      - name: Upload Release Asset BingoViewer.zip
        id: upload-release-asset-bingoviewer-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/BingoViewer/BingoViewer.zip
          asset_name: BingoViewer.zip

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3 binutils

      - uses: ./.github/run-tests

      - name: Upload Release Asset DXRando.zip
        id: upload-release-asset-dxrando-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/DXRando/DXRando.zip
          asset_name: DXRandoInstaller-Linux.zip

      - name: Upload Release Asset BingoViewer.zip
        id: upload-release-asset-bingoviewer-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/BingoViewer/BingoViewer.zip
          asset_name: BingoViewer-Linux.zip
