name: release-windows

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}

    - uses: ./.github/run-tests

    - run: Compress-Archive -Path dist/* -Destination DXRando.zip

    - name: Upload Release Asset DXRando.zip
      id: upload-release-asset-dxrando-zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: DXRando.zip
        asset_name: DXRando.zip
        asset_content_type: application/octet-stream
